const LANGUAGES = {
  uz: {
    choose_lang: "🇺🇿 Tilni tanlang:",
    welcome: "👋 Botga xush kelibsiz!",
    welcome_back: "👋 Xush kelibsiz!",
    main_menu_auction: "📅 Auksion",
    main_menu_earn_stars: "💼 stars ishlash",
    sub_check_button: "✅ A'zolikni tekshirish",
    sub_incomplete: "⚠️ Quyidagi kanallarga a'zo bo'ling:",
    main_menu_withdraw: "📤 Pul yechish",
    main_menu_deposit: "📩 Pul kiritish",
    main_menu_balance: "💰 Hisobim",
    main_menu_daily_bonus: "🎁 Kunlik bonus",
    main_menu_payments: "📋 To'lovlar",
    main_menu_help: "🆘 Yordam",
    main_menu_broadcast: "📢 Hamma foydalanuvchilarga xabar",
    back_button: "🔙 Orqaga",
    sub_success: "✅ Siz barcha kanallarga obuna bo'lgansiz!",
    balance_info_title: "<b>🏦 HISOB MA'LUMOTLARINGIZ</b>",
    balance_info_name: "👤 <b>Ismingiz:</b>",
    balance_info_id: "🆔 <b>Telegram ID:</b>",
    balance_info_acc_num: "🔢 <b>Hisob raqami:</b>",
    balance_info_referrals: "👥 <b>Taklif qilgan do'stlaringiz:</b>",
    balance_info_status: "🎖 <b>Status:</b>",
    balance_info_balance: "💰 <b>Balans:</b>",
    balance_info_deposited: "➕ <b>Kiritilgan:</b>",
    balance_info_withdrawn: "➖ <b>Yechilgan:</b>",
    balance_info_date: "📅 <b>Sana:</b>",
    balance_info_time: "⏰",
    balance_btn_deposit_stars: "📩 ⭐ kiritish",
    balance_btn_withdraw_stars: "📤 ⭐ yechish",
    auction_rules_title: "👨‍⚖️ <b>Auktsion qoidalari</b>:",
    auction_rules_1: "⚜️ Auksionni 1⭐ dan boshlashingiz mumkin.",
    auction_rules_2: "⚜️ Auksion 10 ta garovga yetganda tugashi mumkin.",
    auction_rules_3: "⚜️ Har qanday ishtirokchi oldingi garovni oshirishi mumkin.",
    auction_rules_4: "⚜️ Maksimal o'sish bosqichi - 10 ⭐.",
    auction_rules_5: "⚜️ Garov ko'tarilgandan so'ng, auksion 10 daqiqaga uzaytiriladi.",
    auction_rules_6: "⚜️ Taymer nolga yetganda, oxirgi garovchi g'olib bo'ladi.",
    auction_rules_7: "⚜️ Foydalanuvchi ketma-ket pul tika olmaydi.",
    auction_rules_8: "⚜️ G'olib bankdan 90% oladi.",
    auction_btn_watch: "👁 Auksionni kuzatish",
    auction_btn_start: "🚀 Auksionni boshlash",
    auction_ask_start_bid: "Boshlang'ich tikish miqdorini kiriting:",
    auction_invalid_bid_amount: "❌ Noto'g'ri miqdor!",
    auction_invalid_bid_format: "❌ Iltimos, faqat raqam kiriting!",
    auction_insufficient_funds: "❌ Balansingizda yetarli mablag' yo'q!",
    referral_link_title: "⚡️ Sizning taklif havolangiz:",
    referral_info_1: "🖇️ 1 ta taklif uchun 2 ⭐ beriladi.",
    referral_info_2: "💸 Do'stlaringizni va tanishlaringizni taklif qiling!",
    referral_count: "👤 Sizning takliflaringiz:",
    referral_btn_share: "📤 Ulashish",
    referral_btn_top: "🏆 TOP 10 taklifchilar",
    top_referrals_title: "🏆 <b>TOP 10 Taklifchilar</b>",
    new_referral_bonus: "🎉 Yangi taklif: @{username} obuna bo'ldi va sizga 2 ⭐!",
    deposit_ask_amount: "Necha ⭐ kiritmoqchisiz?",
    deposit_request_sent: "✅ Sizning so'rovingiz yuborildi.",
    deposit_user_confirmed: "✅ {amount} ⭐ balansingizga qo'shildi!",
    withdraw_ask_username: "@username ni kiriting:",
    withdraw_confirm_username: "Shu username ga yechish: @{username}?",
    withdraw_yes: "✅ Ha",
    withdraw_no: "❌ Yo'q",
    withdraw_ask_method: "💸 Qaysi usulda yechmoqchisiz?",
    withdraw_premium_3_month_1000: "1000 ⭐ 3 oy Premium",
    withdraw_premium_6_month_1500: "1500 ⭐ 6 oy Premium",
    withdraw_insufficient_funds: "❌ Yetarli yulduz yo'q.",
    withdraw_request_sent: "✅ So'rovingiz yuborildi.",
    withdraw_cancelled: "❌ Yechish bekor qilindi.",
    withdraw_success_user: "✅ {amount} ⭐ muvaffaqiyatli yechildi!\n💳 Yechilgan: @{username}",
    withdraw_success_admin_alert: "✅ To'lov tasdiqlandi!",
    daily_bonus_taken: "⏳ Siz bonus oldingiz.\nYangi bonus {hours}s {minutes}d {seconds}s dan keyin.",
    daily_bonus_received: "🎁 Tabriklaymiz! Bonus {amount} ⭐.",
    payment_history_deposited: "📥 Kiritilgan yulduzlar:",
    payment_history_withdrawn: "📤 Yechilgan yulduzlar:",
    help_message: "Nima haqida yozmoqchisiz? 😊",
    auction_already_active: "❗ Auksion allaqachon boshlangan!",
    auction_no_funds: "❌ Yetarli mablag' yo'q (minimum 1⭐).",
    auction_started_msg: "🚀 Auksion boshlandi!",
    auction_not_active: "❌ Auksion faol emas.",
    auction_bid_self_error: "❌ Ketma-ket tikib bo'lmaydi!",
    auction_bid_low_error: "❌ Tikish yuqori bo'lishi kerak!",
    auction_bid_max_error: "❌ Maksimal 10⭐ bir marta!",
    auction_bid_success: "✅ Siz {amount}⭐ tikdingiz!",
  },
  ru: {
    choose_lang: "🇷🇺 Выберите язык:",
    welcome: "👋 Добро пожаловать в бот!",
    welcome_back: "👋 Добро пожаловать!",
    main_menu_auction: "📅 Аукцион",
    main_menu_earn_stars: "💼 Заработать звезды",
    sub_check_button: "✅ Проверить подписку",
    sub_incomplete: "⚠️ Подпишитесь на следующие каналы:",
    main_menu_withdraw: "📤 Вывод средств",
    main_menu_deposit: "📩 Пополнить баланс",
    main_menu_balance: "💰 Мой баланс",
    main_menu_daily_bonus: "🎁 Ежедневный бонус",
    main_menu_payments: "📋 Платежи",
    main_menu_help: "🆘 Помощь",
    main_menu_broadcast: "📢 Рассылка",
    back_button: "🔙 Назад",
    sub_success: "✅ Вы подписаны на все каналы!",
    balance_info_title: "<b>🏦 ИНФОРМАЦИЯ О СЧЕТЕ</b>",
    balance_info_name: "👤 <b>Ваше имя:</b>",
    balance_info_id: "🆔 <b>Telegram ID:</b>",
    balance_info_acc_num: "🔢 <b>Номер счета:</b>",
    balance_info_referrals: "👥 <b>Приглашенные друзья:</b>",
    balance_info_status: "🎖 <b>Статус:</b>",
    balance_info_balance: "💰 <b>Баланс:</b>",
    balance_info_deposited: "➕ <b>Пополнено:</b>",
    balance_info_withdrawn: "➖ <b>Выведено:</b>",
    balance_info_date: "📅 <b>Дата:</b>",
    balance_info_time: "⏰",
    balance_btn_deposit_stars: "📩 ⭐ пополнить",
    balance_btn_withdraw_stars: "📤 ⭐ вывести",
    auction_rules_title: "👨‍⚖️ <b>Правила аукциона</b>:",
    auction_rules_1: "⚜️ Вы можете начать аукцион с 1⭐.",
    auction_rules_2: "⚜️ Аукцион может завершиться при 10 ставках.",
    auction_rules_3: "⚜️ Любой участник может перебить ставку.",
    auction_rules_4: "⚜️ Максимальный шаг - 10 ⭐.",
    auction_rules_5: "⚜️ После ставки аукцион продлевается на 10 минут.",
    auction_rules_6: "⚜️ Последний ставщик побеждает.",
    auction_rules_7: "⚜️ Нельзя ставить подряд.",
    auction_rules_8: "⚜️ Победитель получает 90% банка.",
    auction_btn_watch: "👁 Следить за аукционом",
    auction_btn_start: "🚀 Начать аукцион",
    auction_ask_start_bid: "Введите начальную ставку:",
    auction_invalid_bid_amount: "❌ Неверная сумма!",
    auction_invalid_bid_format: "❌ Только цифры!",
    auction_insufficient_funds: "❌ Недостаточно средств!",
    referral_link_title: "⚡️ Ваша реферальная ссылка:",
    referral_info_1: "🖇️ 2 ⭐ за 1 приглашение.",
    referral_info_2: "💸 Приглашайте друзей!",
    referral_count: "👤 Ваши приглашения:",
    referral_btn_share: "📤 Поделиться",
    referral_btn_top: "🏆 ТОП 10",
    top_referrals_title: "🏆 <b>ТОП 10 Пригласивших</b>",
    new_referral_bonus: "🎉 @{username} подписался, вам 2 ⭐!",
    deposit_ask_amount: "Сколько ⭐ пополнить?",
    deposit_request_sent: "✅ Запрос отправлен.",
    deposit_user_confirmed: "✅ {amount} ⭐ добавлено на баланс!",
    withdraw_ask_username: "Введите @username:",
    withdraw_confirm_username: "Вывести на @{username}?",
    withdraw_yes: "✅ Да",
    withdraw_no: "❌ Нет",
    withdraw_ask_method: "💸 Способ вывода?",
    withdraw_premium_3_month_1000: "1000 ⭐ 3 месяца Premium",
    withdraw_premium_6_month_1500: "1500 ⭐ 6 месяцев Premium",
    withdraw_insufficient_funds: "❌ Недостаточно звезд.",
    withdraw_request_sent: "✅ Запрос отправлен.",
    withdraw_cancelled: "❌ Вывод отменен.",
    withdraw_success_user: "✅ {amount} ⭐ выведено!\n💳 На: @{username}",
    withdraw_success_admin_alert: "✅ Платеж подтвержден!",
    daily_bonus_taken: "⏳ Бонус уже получен.\nЧерез {hours}ч {minutes}м {seconds}с.",
    daily_bonus_received: "🎁 Бонус {amount} ⭐ получен!",
    payment_history_deposited: "📥 Пополнено:",
    payment_history_withdrawn: "📤 Выведено:",
    help_message: "О чём хотите написать? 😊",
    auction_already_active: "❗ Аукцион уже идёт!",
    auction_no_funds: "❌ Недостаточно средств (мин 1⭐).",
    auction_started_msg: "🚀 Аукцион начался!",
    auction_not_active: "❌ Аукцион неактивен.",
    auction_bid_self_error: "❌ Нельзя ставить подряд!",
    auction_bid_low_error: "❌ Ставка должна быть выше!",
    auction_bid_max_error: "❌ Макс 10⭐ за раз!",
    auction_bid_success: "✅ Ставка {amount}⭐ принята!",
  },
  en: {
    choose_lang: "🇬🇧 Choose language:",
    welcome: "👋 Welcome to the bot!",
    welcome_back: "👋 Welcome back!",
    main_menu_auction: "📅 Auction",
    main_menu_earn_stars: "💼 Earn Stars",
    sub_check_button: "✅ Check Subscription",
    sub_incomplete: "⚠️ Please subscribe to these channels:",
    main_menu_withdraw: "📤 Withdraw",
    main_menu_deposit: "📩 Deposit",
    main_menu_balance: "💰 My Balance",
    main_menu_daily_bonus: "🎁 Daily Bonus",
    main_menu_payments: "📋 Payments",
    main_menu_help: "🆘 Help",
    main_menu_broadcast: "📢 Broadcast",
    back_button: "🔙 Back",
    sub_success: "✅ You are subscribed to all channels!",
    balance_info_title: "<b>🏦 ACCOUNT INFORMATION</b>",
    balance_info_name: "👤 <b>Your Name:</b>",
    balance_info_id: "🆔 <b>Telegram ID:</b>",
    balance_info_acc_num: "🔢 <b>Account Number:</b>",
    balance_info_referrals: "👥 <b>Invited Friends:</b>",
    balance_info_status: "🎖 <b>Status:</b>",
    balance_info_balance: "💰 <b>Balance:</b>",
    balance_info_deposited: "➕ <b>Deposited:</b>",
    balance_info_withdrawn: "➖ <b>Withdrawn:</b>",
    balance_info_date: "📅 <b>Date:</b>",
    balance_info_time: "⏰",
    balance_btn_deposit_stars: "📩 ⭐ Deposit",
    balance_btn_withdraw_stars: "📤 ⭐ Withdraw",
    auction_rules_title: "👨‍⚖️ <b>Auction Rules</b>:",
    auction_rules_1: "⚜️ Start auction from 1⭐.",
    auction_rules_2: "⚜️ Auction ends at 10 bids.",
    auction_rules_3: "⚜️ Anyone can outbid.",
    auction_rules_4: "⚜️ Max increment 10⭐.",
    auction_rules_5: "⚜️ Bid extends time by 10 min.",
    auction_rules_6: "⚜️ Last bidder wins.",
    auction_rules_7: "⚜️ No consecutive bids.",
    auction_rules_8: "⚜️ Winner gets 90% of bank.",
    auction_btn_watch: "👁 Watch Auction",
    auction_btn_start: "🚀 Start Auction",
    auction_ask_start_bid: "Enter initial bid:",
    auction_invalid_bid_amount: "❌ Invalid amount!",
    auction_invalid_bid_format: "❌ Numbers only!",
    auction_insufficient_funds: "❌ Insufficient funds!",
    referral_link_title: "⚡️ Your referral link:",
    referral_info_1: "🖇️ 2 ⭐ per referral.",
    referral_info_2: "💸 Invite your friends!",
    referral_count: "👤 Your referrals:",
    referral_btn_share: "📤 Share",
    referral_btn_top: "🏆 TOP 10",
    top_referrals_title: "🏆 <b>TOP 10 Referrers</b>",
    new_referral_bonus: "🎉 @{username} joined, you get 2 ⭐!",
    deposit_ask_amount: "How many ⭐ to deposit?",
    deposit_request_sent: "✅ Request sent.",
    deposit_user_confirmed: "✅ {amount} ⭐ added to balance!",
    withdraw_ask_username: "Enter @username:",
    withdraw_confirm_username: "Withdraw to @{username}?",
    withdraw_yes: "✅ Yes",
    withdraw_no: "❌ No",
    withdraw_ask_method: "💸 Withdrawal method?",
    withdraw_premium_3_month_1000: "1000 ⭐ 3 months Premium",
    withdraw_premium_6_month_1500: "1500 ⭐ 6 months Premium",
    withdraw_insufficient_funds: "❌ Not enough stars.",
    withdraw_request_sent: "✅ Request sent.",
    withdraw_cancelled: "❌ Withdrawal cancelled.",
    withdraw_success_user: "✅ {amount} ⭐ withdrawn!\n💳 To: @{username}",
    withdraw_success_admin_alert: "✅ Payment confirmed!",
    daily_bonus_taken: "⏳ Already claimed.\n{hours}h {minutes}m {seconds}s left.",
    daily_bonus_received: "🎁 Bonus {amount} ⭐ received!",
    payment_history_deposited: "📥 Stars deposited:",
    payment_history_withdrawn: "📤 Stars withdrawn:",
    help_message: "What would you like to ask? 😊",
    auction_already_active: "❗ Auction is already active!",
    auction_no_funds: "❌ Insufficient funds (min 1⭐).",
    auction_started_msg: "🚀 Auction started!",
    auction_not_active: "❌ Auction is not active.",
    auction_bid_self_error: "❌ Cannot bid consecutively!",
    auction_bid_low_error: "❌ Bid must be higher!",
    auction_bid_max_error: "❌ Max 10⭐ at a time!",
    auction_bid_success: "✅ Bid of {amount}⭐ placed!",
  }
};

function getText(lang, key, vars = {}) {
  const l = LANGUAGES[lang] || LANGUAGES['uz'];
  let text = l[key] || '';
  Object.entries(vars).forEach(([k, v]) => {
    text = text.replace(new RegExp(`\\{${k}\\}`, 'g'), v);
  });
  return text;
}

module.exports = { LANGUAGES, getText };
